import { pool } from './pool.js'

const bootstrapSql = `
-- MVP scope only.
-- Do not create or copy dbo.stg_CHECKINOUT or any of its records into Postgres.
-- \`marcaciones\` is preserved as a business table, seeded manually for demo purposes.

create table if not exists cargos (
  id_cargo integer generated by default as identity primary key,
  nombre_cargo varchar(100) not null unique,
  descripcion varchar(250),
  activo boolean not null default true
);

create table if not exists areas (
  id_area integer generated by default as identity primary key,
  nombre_area varchar(100) not null unique,
  descripcion varchar(250),
  activo boolean not null default true
);

create table if not exists condiciones_laborales (
  id_condicion_laboral integer generated by default as identity primary key,
  nombre_condicion_laboral varchar(100) not null unique,
  descripcion varchar(250),
  activo boolean not null default true
);

create table if not exists trabajadores (
  id_trabajador integer generated by default as identity primary key,
  dni char(8),
  codigo_trabajador varchar(20),
  codigo_biometrico varchar(30),
  apellidos varchar(100) not null,
  nombres varchar(100) not null,
  id_cargo integer references cargos (id_cargo),
  id_area integer references areas (id_area),
  id_condicion_laboral integer references condiciones_laborales (id_condicion_laboral),
  fecha_ingreso date,
  activo boolean not null default true,
  correo varchar(150),
  telefono varchar(30),
  observacion varchar(500),
  fecha_registro timestamp(0) not null default current_timestamp
);

create unique index if not exists ux_trabajadores_codigo_trabajador
  on trabajadores (codigo_trabajador)
  where codigo_trabajador is not null;

create index if not exists ix_trabajadores_area on trabajadores (id_area, activo);
create index if not exists ix_trabajadores_cargo on trabajadores (id_cargo, activo);
create index if not exists ix_trabajadores_condicion_laboral on trabajadores (id_condicion_laboral, activo);

create table if not exists trabajador_biometrico (
  id_trabajador_biometrico integer generated by default as identity primary key,
  id_trabajador integer not null unique references trabajadores (id_trabajador),
  userid_biometrico integer not null unique,
  activo boolean not null default true,
  fecha_registro timestamp(0) not null default current_timestamp,
  observacion varchar(250)
);

create table if not exists marcaciones (
  id_marcacion bigint generated by default as identity primary key,
  id_trabajador integer not null references trabajadores (id_trabajador),
  fecha_hora_marcacion timestamp(0) not null,
  fecha_marcacion date generated always as (fecha_hora_marcacion::date) stored,
  hora_marcacion time(0) generated always as (fecha_hora_marcacion::time(0)) stored,
  constraint uq_marcaciones_trabajador_fecha_hora unique (id_trabajador, fecha_hora_marcacion)
);

create index if not exists ix_marcaciones_trabajador_fecha_hora
  on marcaciones (id_trabajador, fecha_hora_marcacion);

create table if not exists horarios (
  id_horario integer generated by default as identity primary key,
  codigo_horario varchar(20) not null unique,
  nombre_horario varchar(100) not null unique,
  hora_entrada time(0) not null,
  hora_salida time(0) not null,
  tolerancia_entrada_minutos integer not null default 10,
  tolerancia_salida_minutos integer not null default 0,
  descripcion varchar(250),
  activo boolean not null default true,
  constraint ck_horarios_tolerancias check (
    tolerancia_entrada_minutos >= 0 and tolerancia_salida_minutos >= 0
  ),
  constraint ck_horarios_horas check (hora_salida <> hora_entrada)
);

insert into cargos (id_cargo, nombre_cargo, descripcion, activo)
values
  (1, 'Prof. de Aula', 'Docente responsable de aula', true),
  (2, 'Aux. Educacion', 'Apoyo en actividades educativas', true),
  (3, 'Administrativo', 'Personal administrativo', true),
  (4, 'Director', 'Responsable de direccion institucional', true)
on conflict (id_cargo) do nothing;

insert into areas (id_area, nombre_area, descripcion, activo)
values
  (1, 'Inicial', 'Nivel inicial', true),
  (2, 'Primaria', 'Nivel primaria', true),
  (3, 'Secundaria', 'Nivel secundaria', true),
  (4, 'Administracion', 'Area administrativa', true)
on conflict (id_area) do nothing;

insert into condiciones_laborales (id_condicion_laboral, nombre_condicion_laboral, descripcion, activo)
values
  (1, 'Nombrado', 'Personal nombrado', true),
  (2, 'Contratado', 'Personal contratado', true),
  (3, 'CAS', 'Contrato administrativo de servicios', true),
  (4, 'Practicante', 'Personal en practicas', true)
on conflict (id_condicion_laboral) do nothing;

insert into trabajadores (
  id_trabajador,
  dni,
  codigo_trabajador,
  apellidos,
  nombres,
  id_cargo,
  id_area,
  id_condicion_laboral,
  fecha_ingreso,
  activo,
  correo,
  telefono,
  observacion,
  codigo_biometrico
)
values
  (1, '45879612', 'TRA-001', 'Alvarado Mendez', 'Ricardo', 3, 4, 1, '2021-03-01', true, 'ricardo.alvarado@institucion.edu.pe', '987654321', 'Vinculacion biometrica validada', 'BIO-001'),
  (2, '70142536', 'TRA-002', 'Caceres Vaca', 'Elena', 2, 1, 2, '2024-02-15', true, 'elena.caceres@institucion.edu.pe', '956223410', 'Pendiente de confirmacion en modulo biometrico', 'BIO-002'),
  (3, '41258963', 'TRA-003', 'Delgado Rojas', 'Marcos', 1, 2, 1, '2019-08-01', true, 'marcos.delgado@institucion.edu.pe', '934552210', 'Sin USERID asociado todavia', null),
  (4, '42115599', 'TRA-004', 'Gomez Paz', 'Claudia', 3, 4, 3, '2023-01-10', false, 'claudia.gomez@institucion.edu.pe', '966145782', 'Trabajadora temporal actualmente inactiva', 'BIO-004'),
  (5, '47885544', 'TRA-005', 'Herrera Limo', 'Julian', 4, 3, 1, '2017-05-04', true, 'julian.herrera@institucion.edu.pe', '955008741', 'Alta prioridad en reportes de control', 'BIO-005'),
  (6, '73544018', null, 'Soto Quispe', 'Daniela', 1, 1, 4, '2026-03-18', true, 'daniela.soto@institucion.edu.pe', '944221908', 'Codigo interno pendiente de asignacion', 'BIO-006')
on conflict (id_trabajador) do nothing;

insert into trabajador_biometrico (id_trabajador_biometrico, id_trabajador, userid_biometrico, activo, observacion)
values
  (1, 1, 1001, true, 'Vinculado correctamente'),
  (2, 4, 1004, true, 'Vinculado correctamente'),
  (3, 5, 1005, true, 'Vinculado correctamente')
on conflict (id_trabajador_biometrico) do nothing;

insert into marcaciones (id_trabajador, fecha_hora_marcacion)
values
  (1, '2026-04-01 07:58:00'),
  (1, '2026-04-01 13:04:00'),
  (1, '2026-04-02 08:03:00'),
  (1, '2026-04-02 13:01:00'),
  (2, '2026-04-01 08:12:00'),
  (2, '2026-04-01 13:00:00'),
  (2, '2026-04-02 08:06:00'),
  (2, '2026-04-02 12:56:00'),
  (3, '2026-04-01 07:49:00'),
  (3, '2026-04-01 13:08:00'),
  (4, '2026-04-01 08:01:00'),
  (4, '2026-04-01 12:31:00'),
  (5, '2026-04-01 07:44:00'),
  (5, '2026-04-01 13:16:00'),
  (6, '2026-04-01 08:18:00')
on conflict (id_trabajador, fecha_hora_marcacion) do nothing;

insert into horarios (
  id_horario,
  codigo_horario,
  nombre_horario,
  hora_entrada,
  hora_salida,
  tolerancia_entrada_minutos,
  tolerancia_salida_minutos,
  descripcion,
  activo
)
values
  (1, 'L-V-0800-1830', 'Lunes a Viernes 08:00 a 18:30', '08:00', '18:30', 0, 0, 'Horario fijo de lunes a viernes', true),
  (2, 'L-V-0740-1555', 'Lunes a Viernes 07:40 a 15:55', '07:40', '15:55', 0, 0, 'Horario fijo de lunes a viernes', true),
  (3, 'L-V-1230-2030', 'Lunes a Viernes 12:30 a 20:30', '12:30', '20:30', 0, 0, 'Horario fijo de lunes a viernes', true),
  (4, 'L-V-1230-1830', 'Lunes a Viernes 12:30 a 18:30', '12:30', '18:30', 0, 0, 'Horario fijo de lunes a viernes', true),
  (5, 'L-V-1300-1830', 'Lunes a Viernes 13:00 a 18:30', '13:00', '18:30', 0, 0, 'Horario fijo de lunes a viernes', true),
  (6, 'L-V-0800-1245', 'Lunes a Viernes 08:00 a 12:45', '08:00', '12:45', 0, 0, 'Horario fijo de lunes a viernes', true),
  (7, 'V-1300-1800', 'Variable 13:00 a 18:00', '13:00', '18:00', 0, 0, 'Horario variable por dia', true),
  (8, 'V-1420-1800', 'Variable 14:20 a 18:00', '14:20', '18:00', 0, 0, 'Horario variable por dia', true)
on conflict (id_horario) do nothing;
`

let bootstrapped = false

export async function ensureDatabaseReady() {
  if (bootstrapped) {
    return
  }

  const statements = bootstrapSql
    .split(';')
    .map((statement) => statement.trim())
    .filter(Boolean)

  for (const statement of statements) {
    await pool.query(statement)
  }

  bootstrapped = true
}
